$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: nyc-taxi-env
image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04
conda_file: ../../environments/conda_train.yml
description: nyc-taxi-env
