name:
channels:
  - conda-forge
dependencies:
  - python=3.8.5
  - pip=22.3.1
  - pip:
      - azureml-mlflow==1.45.0
      - mlflow==1.30.0
      - scikit-learn==1.0.2
      - pandas==1.1.5
      - joblib==1.0.0
      - matplotlib==3.3.3
      - azureml-defaults==1.47.0
      - black[jupyter]==22.8.0
      - pre-commit==2.20.0
      - papermill==2.4.0
      - ipykernel==6.6.0
      - raiwidgets==0.23.0
      - numpy<1.24.0
