$schema: https://azuremlschemas.azureedge.net/latest/batchDeployment.schema.json
name: batch-deployment
description: custom batch deployment
endpoint_name: batch-endpoint
model: azureml:nyc_taxi:1
code_configuration:
  code: ../src/deploy/
  scoring_script: score.py
environment: azureml:nyc-taxi-env:1
compute: azureml:cpu-cluster
resources:
  instance_count: 1
max_concurrency_per_instance: 2
mini_batch_size: 10
output_action: append_row
output_file_name: predictions.csv
retry_settings:
  max_retries: 3
  timeout: 30
error_threshold: -1
logging_level: info
