$schema: https://azuremlschemas.azureedge.net/latest/batchDeployment.schema.json
name: batch-deployment
endpoint_name: batch-endpoint
code_configuration:
  code: ../src/deploy
  scoring_script: score.py
model: azureml:nyc_taxi@latest
environment: azureml:nyc-taxi-env@latest
compute: azureml:cpu-cluster
resources:
  instance_count: 2
max_concurrency_per_instance: 2
mini_batch_size: 10
output_action: append_row
output_file_name: predictions.csv
retry_settings:
  max_retries: 3
  timeout: 30
error_threshold: -1
logging_level: info