$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
experiment_name: train_nyx_taxi
description: train_nyx_taxi
type: command
code: ../src/model
command: >-
  python train_nyx_taxi.py 
  --input_data ${{inputs.diabetes_data}}
  --output_dir ${{outputs.output_dir}}
environment: azureml:env-nyx-taxi@latest
inputs:
  diabetes_data:
    type: uri_file
    path: azureml:nyx_taxi_dataset@latest
outputs:
  output_dir:
    type: uri_folder 
    path: azureml://datastores/workspaceblobstore/paths/nyx-taxi/
    mode: mount
compute: azureml:demo-cpucluster1