$schema: https://azuremlschemas.azureedge.net/latest/batchDeployment.schema.json
name: batch-deployment
description: custom batch deployment
model: azureml:nyc_taxi@latest
code_configuration:
  code: ../../src/deploy/batch/
  scoring_script: score.py
environment: azureml:nyc-taxi-env@latest
compute: azureml:cpu-cluster
resources:
  instance_count: 1
max_concurrency_per_instance: 2
mini_batch_size: 10
output_action: append_row
output_file_name: predictions.csv
retry_settings:
  max_retries: 3
  timeout: 30
error_threshold: -1
logging_level: info
