$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue
model: azureml:nyc_taxi:1
code_configuration:
  code: ../../src/deploy/online/
  scoring_script: score.py
environment: azureml:nyc-taxi-env@latest
instance_type: Standard_DS4_v2
instance_count: 1
