name: Smoke Testing for Notebook
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
      - cron: "0 0 * * *"
  workflow_dispatch:


jobs:
  smoke-testing-notebook:
    name: Smoke Testing for Notebook
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup python
      uses: actions/setup-python@v4.2.0
      with:
        python-version: "3.9"
    - name: Create conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: mlops-train
        environment-file: environments/conda_train.yml
    - name : Kernel configuration
      run: |
        python -m ipykernel install --user --name mlops-train
      shell: bash -el {0}
    - name: Run Notebook for experiment
      run: |
        papermill train-experiment.ipynb output.ipynb -k mlops-train
      working-directory: notebooks
      shell: bash -el {0}
    - name: Run Notebook for mlflow
      run: |
        papermill train-mlflow-local.ipynb output.ipynb -k mlops-train
      working-directory: notebooks
      shell: bash -el {0}
    - name: Run Notebook for responsible ai debugging
      run: |
        papermill train-model-debugging.ipynb output.ipynb -k mlops-train
      working-directory: notebooks
      shell: bash -el {0}
