name: Smoke Testing for Notebook
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
      - cron: "0 0 * * *"
  workflow_dispatch:


jobs:
  smoke-testing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup python
      uses: actions/setup-python@v4.2.0
      with:
        python-version: "3.9"
    - name: Create conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: mlops-train
        environment-file: environments/conda_train.yml
        python-version: 3.8.5
    - name : conda info
      run: |
        conda info
        conda list
        which papermill
      shell: bash
    - name: Run Notebook
      run: |
        papermill train-prototyping.ipynb -
      working-directory: notebooks
      shell: bash
